import "../globals.css";
import type { Metadata } from "next";
import { Inter as FontSans, Space_Grotesk } from "next/font/google";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import LearnHeaderComponent from "./(learn_component)/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
const space = Space_Grotesk({ subsets: ["latin"] });

export default function LearnLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const containerStyle = {
    backgroundImage: `url('/lessons_bg.png')`,
    height: "98vh", // Set the height as needed
    width: "100%",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
  };

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "min-h-screen bg-background mx-auto font-sans antialiased ",
            space
          )}
        >
          <div
            className="flex flex-col w-full px-8 mx-auto lg:px-20"
            style={containerStyle}
          >
            {/* header */}
            <LearnHeaderComponent />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
