import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={
            "min-h-screen bg-background mx-auto font-sans  items-center justify-center flex w-full h-screen"
          }
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
