import "../globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { ClerkProvider } from "@clerk/nextjs";
import Header from '@/components/header'
import MobileHeaderComponent from "@/components/mobile_header.component";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
 
export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background mx-auto font-sans antialiased flex flex-col ",  fontSans.variable)}>
        <MobileHeaderComponent />
        <Header />
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
