import React from "react";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body className={inter.className}>

        <div className="  bg-white-600 flex  text-purple-800 space-x-4  h-screen ">
          {/* <div className="flex flex-col w-1/4 justify-center h-screen space-y-2 pl-3 text-white align-middle">
            <Link
              className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-600"
              href="/"
            >
              Home
            </Link>
          
            <Link
              className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-600"
              href="list-questions"
            >
              List Questions
            </Link>
            <Link
              className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-600"
              href="generate-image"
            >
              Generate Image
            </Link>
            <Link
              className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-600"
              href="create-filters"
            >
              Add Filters
            </Link>
          </div> */}
          <div className="flex flex-col w-full  h-screen text-white ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
