import React from "react";
import type { Metadata } from "next";
import "../globals.css";
import Link from "next/link";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Toaster />
          <div className="bg-[#eae8e8] flex text-gray-900 space-x-4  h-screen ">
            <div className="flex flex-col justify-center w-1/4 h-screen pl-3 space-y-2 text-gray-900 align-middle">
              <Link
                className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-300"
                href="/admin/class"
              >
                Classes
              </Link>

              <Link
                className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-300"
                href="/admin/subject"
              >
                Subjects
              </Link>
              <Link
                className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-300"
                href="/admin/topic"
              >
                Topics
              </Link>
              <Link
                className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-300"
                href="/admin/lesson"
              >
                Lessons
              </Link>
              <Link
                className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-300"
                href="/admin/prompt"
              >
                General Prompt
              </Link>
              <Link
                className="items-center p-3 border border-gray-400 rounded-md hover:bg-gray-300"
                href="/admin/config"
              >
                Model Config
              </Link>
            </div>
            <div className="flex flex-col w-full h-screen text-gray-900 ">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
